# Docker Compose override for Apple Silicon (M1/M2) development
# This file automatically applies when running docker-compose on arm64 systems

services:
  # Backend service override for Apple Silicon
  radio-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.arm64
    platform: linux/arm64
    environment:
      # Apple Silicon specific optimizations
      - DOCKER_BUILDPLATFORM=linux/arm64
      - TARGETPLATFORM=linux/arm64
      # Disable problematic features that might cause issues
      - PYTHONDONTWRITEBYTECODE=1
      - PIP_NO_CACHE_DIR=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend service override for Apple Silicon
  radio-app:
    platform: linux/arm64
    environment:
      # Node.js optimizations for Apple Silicon
      - NODE_OPTIONS=--max-old-space-size=2048
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
