# CI-specific Docker Compose configuration
# Optimized for GitHub Actions AMD64 runners with proper platform settings

services:
  # Backend API service for CI
  radio-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      platforms:
        - linux/amd64
    platform: linux/amd64
    container_name: radio-backend-ci
    hostname: radio-backend
    ports:
      - "8000:8000"
    environment:
      # Application settings
      - NODE_ENV=development
      - API_PORT=8000
      - WIFI_INTERFACE=wlan0
      - HOSTNAME=radio

      # Hotspot configuration
      - HOTSPOT_SSID=Radio-Setup
      - HOTSPOT_PASSWORD=radio123
      - HOTSPOT_IP=192.168.4.1

      # CI optimizations
      - PYTHONDONTWRITEBYTECODE=1
      - PIP_NO_CACHE_DIR=1
      - DEBUG=0
    networks:
      - radio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  # Frontend application service for CI
  radio-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      platforms:
        - linux/amd64
      args:
        NODE_VERSION: 20-alpine
    platform: linux/amd64
    container_name: radio-app-ci
    hostname: radio-app
    ports:
      - "3000:3000"
    environment:
      # Application settings
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_DEVTOOLS=false

      # Backend API configuration
      - API_HOST=radio-backend
      - API_PORT=8000

      # Network settings
      - HOSTNAME=radio
      - WIFI_INTERFACE=wlan0

      # CI optimizations
      - NODE_OPTIONS=--max-old-space-size=1024
      - DEBUG=0
      - CHOKIDAR_USEPOLLING=false
    networks:
      - radio-network
    depends_on:
      radio-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

# Custom network for CI
networks:
  radio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
